### PR TITLE
Create Program to find factorial of number using JAVASCRIPT

### PR DESCRIPTION
**Pull request by arpan-pro-learner**
here is the best method or code to find factorial of a number using JS

### CODE REVIEW

**Review by dhanrajdc7 — APPROVED** [review]

**Comment by arpan-pro-learner** [comment]
thank you so much bro for merging my pull request 
i want to ask one thing can i create 3 more pull request in this same repo will they will be counted in hacktoberfest

**Comment by dhanrajdc7** [comment]
Yes 👍🏻 it will be counted in hacktoberfest

**Comment by arpan-pro-learner** [comment]
ok bro i thought it would be marked as spam if i create  4 pull request in same repo

**Comment by dhanrajdc7** [comment]
No, you can submit 4 prs in one repo.
No Problem 😉

**Comment by arpan-pro-learner** [comment]
ok brother ones again thanks you so much for making this repo 
I am going to add 3 more pull request soon 
and I am also going to subscribe to your channel as a part of appreciation

**Comment by dhanrajdc7** [comment]
Thank You So Much 😊

**Pull request merged**
