### PR TITLE
Create Factorial of number sg

### PR DESCRIPTION
**Pull request by sg5915076**
Optimized Code for Factorial of number in C programming quickly.

### CODE REVIEW

**Comment by sg5915076** [comment]
optimized code of largest element in array in c programming

**Review by dhanrajdc7 — APPROVED** [review]

**Comment by sg5915076** [comment]
Thank you 😊

**Comment by sg5915076** [comment]
Please add my another pull requests

**Comment by sg5915076** [comment]
Hello, I want to ask you that why it will showing -1 day
Is there any problem?

**Pull request merged**
